### PR TITLE
SM: Updated links & few edits

### PR DESCRIPTION
**Pull request by smusula**

### CODE REVIEW

**Comment by pld** [comment]
I think you should remove the link to classic. Maybe refer to it as the "previous version" or something, we don't want people to go to classic or think about it.

**Comment by smusula** [comment]
@pld will do

**Comment by cagulas** [comment]
We will post this next Tuesday, since there may not be too much web traffic before the long Easter weekend.

**Comment by pld** [comment]
I don't think this post makes any sense, we can't edit an existing post and pass it off as new, it makes sense to keep the beta post from when launched beta as is, we can change the links and fix grammar or spelling, but we cannot change the date.

The additional information can go in a new post about new permissions on the platform, or a reminder post about how to take advantage of the permissions on the platform.

My suggestion on how to fix is to:
1. change this PR so it doesn't change the date and does not add any new content, i.e. it's just grammar, spelling, and link fixes
2. create a new post that's about how to use permissions in Ona, that includes the new content which is here, it can reiterate information from this post as appropriate but shouldn't be needlessly redundant

How does that sound?

**Pull request merged**
