### PR TITLE
CO: clean up

### PR DESCRIPTION
**Pull request by COpenda**
-Backlinks to the google spreadsheets article, plans page, and google spreadsheets site
-Matt is the author
-Needs graphics, "introducing ona apps" banner and a google spreadsheet integration. or the google spreadsheet ico.

### CODE REVIEW

**Comment by rowo** [comment]
@COpenda So for Ona Apps we're decided not doing two different banners like you requested in https://github.com/onaio/ona/issues/162 or should I still be planning on that?

**Comment by COpenda** [comment]
I think we can have one for Ona Apps and just reuse the RapidPro and Gsheets icons. What do you think? @rowo

**Comment by rowo** [comment]
@COpenda please remember to add extensions to your files. Also, the post file names in the _post folder all use hyphens so you should probably match. I have no idea whether it's a requirement or not but when it comes to technology, it's always good to be consistent.

**Comment by rowo** [comment]
@COpenda take a look at the edits I made to the file you created. If you have any questions about why I made edits please let me know.

**Comment by rowo** [comment]
@COpenda Just a quick thing... when it says, "You can upgrade your account here." or something like that, you need to actually add the links into the post. 

The original post you put up also said, "Subscribe to not miss out on future updates." I took that out because it wasn't linked to anything. What are people supposed to subscribe to?

**Comment by COpenda** [comment]
@rowo sorry i'd missed that, will note that for the next time.

**Pull request merged**
