### PR TITLE
SK: Prediction post for vector tiles

### LINKED ISSUE #81: Add a prediction blog on Vector tile support
According to @COpenda the idea is to write a prediction article for a feature that is yet to be designed but is in the roadmap. 
Vector tile support on Zebra is currently being implemented and i'll write something on this.

### PR DESCRIPTION
**Pull request by skambo**
Closes #81 
@COpenda @rowo please review?

### CODE REVIEW

**Comment by rowo** [comment]
@skambo Are vector tile maps considered an integration? I'm asking because the first two sentences make it seem like they are. Are they accessed via Ona Apps?

**Comment by rowo** [comment]
@skambo is there any chance you have that graphic in a layered format?

**Comment by rowo** [comment]
- The bullets sentences should probably be constructed in a similar fashion. 
  - The second bullet in the "What to expect..." seems oddly worded. It would match the first bullet to say, "Ona maps will be enhanced to be more..." or "Ona maps are enhanced to be more..." or just remove "enhancement" since the list is a list of enhancements, i.e. "Ona maps will be more efficient when loading..." @skambo What does "efficient" mean here? Data transfer or CPU or...?
  - The third and fourth bullets should match the first i.e. "Ona users will be able to build..." Or you can change the first, since it seems like the odd one out. It could be something like "Serve up larger datasets to maps, faster." Though, I don't know what "larger" means in this case. Is it known to everyone that really big datasets don't work on the map? 
- I feel like the "Vector tiles offer two important advantages..." section repeats some of the "What to expect..." section. Certain ideas can be said fewer times (i.e. "make huge maps fast" and "serve up large datasets ... quickly" and "fast map loads") in a benefits-oriented way. More words just means more noise if it's the same point over and over.
- I don't understand how vector tile maps will let me, as a user, build choropleths and point clusters. Are those added automatically to the UI? It's implied that they are.

**Comment by skambo** [comment]
@rowo I've made some edits based on the above and changed the images too, please review once more?

**Comment by rowo** [comment]
@skambo 
- When you say, "When users switch between different views, for example from the map view to the table view, it will be easier to get back to the location you had zoomed in to on the map as your map coverage will be restored to show all your points." Does this mean the zoom level and location of the map view is saved when you switch between tabs? 
- in "Vector tile maps can also be styled when requested, allowing for flexible styling without affecting performance." what does "when requested" mean to a user?

**Comment by skambo** [comment]
@rowo 
On the first point i.e. 

> Does this mean the zoom level and location of the map view is saved when you switch away from the Map tab and back 

@royrutto says it can be done if users want it so it i.e. we can either reset the map or keep it focused on a point if they had zoomed in. From the comment here though it looked like maps would be kept focused on a point if zoomed in https://github.com/onaio/zebra/issues/2634

On the second point, suggestion is to re word from “When requested” as its a bit technical to 

> Data on vector tile maps will only be loaded/requested on the map tab when the user does view by filters and this improves performance

**Comment by rowo** [comment]
@skambo Ok thanks. Point 1: I was just wondering what you meant since mentioning it in this context implies that it has changed, but it hasn't. So I'll make that clearer. But it is good to know the other option is possible. Point 2: Ok.

**Pull request merged**
