### PR TITLE
Xls form blog

### PR DESCRIPTION
**Pull request by COpenda**
@rowo please review and merge.

### CODE REVIEW

**Comment by rowo** [comment]
I don't have a problem with the word "huge"

**Comment by rowo** [comment]
@COpenda 
- As mentioned before, please capitalize "Ona"
- Add a .md extension to your file
- What do you think about embedding the video?
- Is the heading "A Recap of The XLSForm Authoring Webinar" necessary? It shows up right below the title which is "XLSForm Webinar Recap"
- Add the link for the Q&A: https://drive.google.com/a/ona.io/file/d/0B1O3i3oVkq5GdGowaHhMMjZVcTQ/view
- Instead of "our social media pages" you could just list them out with direct links.
- Not sure how you feel about serial commas. You don't seem to use them. @pld what do you think? Should we adopt them in our communications or no?

**Comment by COpenda** [comment]
@rowo 
- i like the embedding idea, but not full embedding as that usually slows down sites due to auto downloading. Perhaps do a thumbnail of the video? and a play button to prompt the download only on request...that's possible with jekyll?
- I DO use serial commas. what context are you referring this to?
- Or alternatively just display the social media buttons as hyperlinks? Listing them seems odd to me.

**Comment by COpenda** [comment]
Will be posted on the blog after this [issue](https://github.com/onaio/help/issues/167) has been resolved

**Comment by mberg** [comment]
Embedding of YouTube doesn't slow down sites does it?  It's specifically
designed for this use case no?

**Comment by rowo** [comment]
@COpenda 
- according to http://www.labnol.org/internet/light-youtube-embeds/27941/ a youtube player adds about 400 kb (about the size of 2–3 banner images), but it also provides a workaround. You can try it out. Also I'm not sure if when you talk about "auto downloading" you are talking about the video? Because I think that's a setting.
- Serial comma: "The webinar covered everything from basic form syntax, question types, validation checks, and advanced tips like grouping questions, apperance attributes, csv uploads and much more."
- Seems file formats (i.e. CSV) should be capitalized since they are acronyms. 
- Please review spelling
- I don't think it's strange to say "Be sure to watch out for the next webinar by following us on [Twitter](#) and [Facebook](#)." Otherwise, buttons seem okay if you think so.

**Comment by rowo** [comment]
@COpenda please make all of the edits recommended in https://github.com/onaio/blog/pull/75#issuecomment-230758516 and https://github.com/onaio/blog/pull/75#issuecomment-230782490 and reassign this PR back to me after you're done. Otherwise, this post can't go out.

**Comment by COpenda** [comment]
@rowo made the changes.
I don't know how to go about embedding stuff on github if you could do that please as i learn how to, else everything is ready on my end unless there's something i've missed

**Comment by rowo** [comment]
@COpenda I added the video, but you missed a few things mentioned above. Please complete the following:
- add a .md file extension
- you are missing some serial comma's (after "csv uploads" and "Twitter"
- some file formats aren't capitalized

**Comment by rowo** [comment]
- You didn't capitalize the file format CSV. We capitalize file formats.
- The .md file extension still isn't there.

**Comment by pld** [comment]
I'm in favor of serial commas, but I have no formal experience in marketing.

**Comment by rowo** [comment]
@pld seems British people think serial commas are for savages. But since we use savage English where it isn't a problem, we'll start using them in our communications to avoid confusing situations like you've mentioned before.

**Comment by pld** [comment]
well, British people also think the European Union is for savages

**Pull request merged**
