### PR TITLE
Ona with R post by Sebastian

### PR DESCRIPTION
**Pull request by COpenda**

### CODE REVIEW

**Comment by pld** [comment]
@COpenda is this the verbatim content in the latest email he sent us?

**Comment by pld** [comment]
There are typos in this, like "grated" in the first paragraph

**Comment by pld** [comment]
Making edits here until it's final, https://docs.google.com/document/d/1Ehf6GoteaSWvdMBuZR-yv-i3OL5Ky924WkWqiT1dghg/edit, no one edit on github, we'll copy over from gdocs when it's ready

**Comment by pld** [comment]
@COpenda also, the title of post file names should follow the same format as the current posts, date then the title all lowercase with underscores

**Comment by rowo** [comment]
Is there a better ending line than "The file will have the current date attached to the file name."

What could work better — and you see this in magazines all the time — is to break out the example into it's own section that you can jump to without reading the entire article or you can skip and the article still works. This would let you end the post properly without having to worry about working the dry app description into the narrative flow.

**Comment by COpenda** [comment]
@rowo it could end with some closing remarks from @pld something in the lines of "...it's exciting to hear of the innovative ways our users enhance the platform to make life easier. What innovative ways are you using Ona? We'd like to hear from you. email us on: marketing@ona.io (can we have a group email for marketing)......"

**Comment by Santei** [comment]
@pld @COpenda @rowo I love the blog. However, while all this content is pertinent, it is too verbose, in my opinion, with no much non-textual content. I believe this post should enlighten people on how they can use ona.R and _probably_ a few statistical things they could do with R. For example a scatter plot or some kind of plot from the data would help highlight this. Unless the data is private, a few images would be great.

**Comment by COpenda** [comment]
Thanks @Santei the title is misleading for the context of the article. It's more of how they "did" (How they used Ona with R )than "how to". For how to, in the case of Santei, the expectations are a step by step guide on how to use Ona with R to automate your analysis and feedback. We should consider rephrasing the title to something like "How Carbon Forest use Ona with R to automate analysis and feedback"

**Comment by pld** [comment]
@Santei yea the data is private and it also doesn't include any plots or tables yet, the main thing they're doing is linking it to emails and summary stats (means, basic things like that). I actually asked Sebastian about plots specifically and he said the above, but mentioned he might add them in the next version, so I suggested we do a followup post when it has more advanced capabilities.

@COpenda I like the title you've suggested, I'll make the change.

@rowo if we split out the example into it's own section, the post would end with "All you have to do is select the languages you need the report written in, and the script will know where to find the answer.", given we don't make any other changes. What do you think about @COpenda suggestion, ending with: "We're excited to hear of the innovative ways our users enhance the platform to make life easier. What innovative ways are you using Ona? Let us know! press@ona.io @onadata https://www.facebook.com/onadata."

**Comment by Santei** [comment]
@COpenda @pld okay cool. That makes sense. The next article on ona.R should probably have such. I can volunteer to do such a blogpost :).

**Comment by rowo** [comment]
@pld Yes Chantal's suggestion is good. I didn't mean you would just end it there, I just meant you wouldn't have to connect back to the narrative after explaining details of an example. 

Another benefit of putting the example in a highlighted section is it makes the blog more skimmable. Not sure if there is a style set up.. it could use blockquote or the note styling.

**Comment by pld** [comment]
OK cool, let me give it a shot...

**Comment by COpenda** [comment]
@Santei that would be great. I'll follow up with you for the article

**Comment by rowo** [comment]
I'm getting an error when opening his example survey when logged into ona.io. The error disappears when I log out. 

screen shot 2016-07-21 at 5 41 33 pm

**Comment by pld** [comment]
This is now blocked by https://github.com/onaio/zebra/issues/4454

**Pull request merged**
