### PR TITLE
CO: new post not finished

### PR DESCRIPTION
**Pull request by COpenda**
@rowo please merge

### CODE REVIEW

**Comment by rowo** [comment]
@COpenda Can you write up this post similar to http://blog.ona.io/general/2016/04/04/new-to-ona.html for Mek and yourself?

**Comment by rowo** [comment]
@COpenda I'm removing the images and will merge. Please review how use images in markdown at https://daringfireball.net/projects/markdown/basics

**Comment by pld** [comment]
I think we should add something about what Mek is working on at Ona, bots and ECD and ..., and maybe the same for Chantal, like her first task will be [something specific and useful to the reader]

**Comment by rowo** [comment]
@pld good ideas. @COpenda what do you think?

**Comment by COpenda** [comment]
really good ideas, i'll have a chat with mek tomorrow and make the edits before noon.

**Comment by rowo** [comment]
@COpenda make sure you sync in Github for Desktop before editing. There are updates to this branch.

**Comment by COpenda** [comment]
@rowo ok

**Comment by COpenda** [comment]
@rowo seen the changes made, looks great!

**Pull request merged**
