### PR TITLE
Google sheets

### PR DESCRIPTION
**Pull request by denniswambua**

### CODE REVIEW

**Comment by rowo** [comment]
This can't go up until the documentation is done.

**Comment by rowo** [comment]
@COpenda @denniswambua Waiting to post until documentation is done. Do you know who is working on the documentation?

**Comment by COpenda** [comment]
@rowo this is being done by @faith-mutua and @smusula The doc is completed it's now under review

**Comment by rowo** [comment]
- I made a banner image for this post. You can grab it from https://github.com/onaio/ona/issues/162#issuecomment-231635614. 
- Just an idea — what do you think about slightly [bedazzling](http://www.urbandictionary.com/define.php?term=Bedazzle) the title (and content) for more clickage? Something like "The 6 ways the new Google Sheets + Ona integration can transform your workflow", or "The 6 things you should try with the new Ona + Google Sheets integration", or "6 essential Google Sheets + Ona workflow tips"... you get the idea. Then modifying the content a bit to support that.

**Comment by rowo** [comment]
The Explore panel image isn't going to show up well in the blog format. It's too wide, so it'll show up small. I'd recommend taking a new screen grab with a narrower browser window. This might be something the Support team has done already, so you could check with them..

**Comment by rowo** [comment]
@COpenda ^

**Comment by COpenda** [comment]
@rowo I think "bedazzling" is a good idea. Though i think it's good to keep one plain banner and have the other bedazzled one for social media use. I can work on the content for the banner.

**Comment by COpenda** [comment]
@rowo Narrowed it down to three key points.

 3 reasons you'll love the new Google Sheets + Ona integration

1. **Access data from anywhere through any device.** 
    _Google sheets is a web application, meaning you can access it from anywhere through any device with a internet access._
2. **Collaboration made better**
   The chat and comment functionality enables you to make faster decisions by reaching your team members faster.
3. **Do more with Google Sheets Add-Ons**
   _Unlock a host of powerful Google Sheets add ons and add value to your data _

**Comment by rowo** [comment]
@COpenda For our audience, it could be better to orient the post as a practical how-to (i.e. tips with benefits) rather than a list benefits. This isn't a Buzzfeed audience — these are still M&E people looking for practical substance. The Import Range piece is pretty profound to some people whereas something general like "Do more with Google Sheets Add-Ons Unlock a host of powerful Google Sheets add ons and add value to your data" won't really do much — unless we call out some specific examples or add-ons. I realize that's the extent of that bullet right now, but just reading it over again. Since we have some time, it's something to research and improve. [Survey CTO](http://www.surveycto.com/product/datasets.html) (search for "Sheets") seems to talk about Sheets stuff a little.

**Comment by COpenda** [comment]
@rowo Cool, I'll research some more on it and find out the best way to present it. At some point we'll need to do a test to find out what "language/writing" our audience respond to, and what makes them convert to ascertain that we are chucking out the right content for the right people.

**Comment by rowo** [comment]
@denniswambua Can you take a new screenshot for the Explore panel example? The screenshot is going to need to be readable when shrunk down to 624px wide.

**Comment by denniswambua** [comment]
google_sheet_explore_button

**Comment by pld** [comment]
Wow, that is a compelling screenshot, real-time custom dashboards in Google
sheets, that's a decent sell

**Comment by rowo** [comment]
@denniswambua For future reference, that image size is still too large for the blog. We can use it this time. I'd say you have to make your browser 1/2 that width.

**Comment by rowo** [comment]
Generally, the image will be shrunk to about 2/3 of the size shown above in the Github thread.

**Comment by rowo** [comment]
Documentation is up now, but this is now blocked by https://github.com/onaio/core/issues/1202.

**Comment by skambo** [comment]
@rowo @COpenda onaio/core#1202 is deployed

**Comment by COpenda** [comment]
Thanks @skambo for the alert. @rowo can we proceed with the announcement or are there any other blocking issues?

**Pull request merged**
