### PR TITLE
Ona r integration

### PR DESCRIPTION
**Pull request by jmunene**
JM: Blog post on Ona & R Integration.

### CODE REVIEW

**Comment by rowo** [comment]
@jmunene made a few text edits. Let me know when the package is merged and the post is updated with the link to that and I can merge the PR.

**Comment by pld** [comment]
I proof read it, could probably use another round of proof reading.

**Comment by mberg** [comment]
It would be ideal if we can have this tested by someone else.

This looks great though Jonathan.  We can do a lot of really cool blog
posts about this.

We should build out a reference section in the ona.r repo too

**Comment by Santei** [comment]
I did actually test this today with Jonathan's branch on ona.R, it works well. My only comment was to add a function to install all the required packages  at once since they are quite many.

**Comment by mberg** [comment]
Actually after Roger gives it a skim we can go live. I trust that it works.  We'll find out pretty quickly if it doesn't!  Would be good as we'll get a charts blog post out by the end of the week too.

**Comment by mberg** [comment]
ok awesome

**Comment by jmunene** [comment]
@rowo Ok, will try to run some tests today, using [testthat](https://github.com/hadley/testthat)
@mberg Thanks, yes there are a number of things we can blog about, for ona.R and R as a package

**Pull request merged**
